blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/paulegradie/renaym/blob/main/Renaym.App/README.md
    about: Check out the documentation before opening an issue

